import {createClient} from 'npm:@supabase/supabase-js@2';
const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'GET, POST, PATCH, OPTIONS','Cache-Control':'no-store'};
const reply=(d:unknown,status=200)=>new Response(JSON.stringify(d),{status,headers:{...cors,'Content-Type':'application/json'}});
const error=(m:string,status=400)=>{throw Object.assign(new Error(m),{status})};
const checked=(r:any)=>{if(r.error)throw new Error(r.error.message);return r.data};
const userShape=(u:any)=>({id:u.id,username:u.username,displayName:u.display_name,role:u.role,active:u.active});
function range(kind:string,date:string){if(!['week','month'].includes(kind)||!/^\d{4}-\d{2}-\d{2}$/.test(date))error('请选择有效统计日期');const day=new Date(date+'T00:00:00+08:00');if(!Number.isFinite(+day)||new Date(+day+28800000).toISOString().slice(0,10)!==date)error('日期无效');let s:number,e:number;if(kind==='week'){s=+day-((new Date(+day+28800000).getUTCDay()+6)%7)*86400000;e=s+7*86400000}else{const [y,m]=date.split('-').map(Number);s=Date.UTC(y,m-1,1)-28800000;e=Date.UTC(y,m,1)-28800000}return {start:new Date(s).toISOString(),end:new Date(e).toISOString(),from:new Date(s+28800000).toISOString().slice(0,10),to:new Date(e+28800000-1).toISOString().slice(0,10)}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const url=new URL(req.url),route=url.searchParams.get('route')||'';const token=(req.headers.get('Authorization')||'').replace(/^Bearer /,'');const {data:auth}=await db.auth.getUser(token);let user=null;if(auth.user){const r=await db.from('teachers').select('*').eq('id',auth.user.id).eq('active',true).maybeSingle();user=checked(r)}
if(route==='/api/me')return reply({user:user?userShape(user):null,setup:false});
if(!user)error('请使用学校分配的老师账号登录',401);
const admin=()=>{if(user.role!=='admin')error('仅管理员可操作',403)};
if(route==='/api/users'){admin();if(req.method==='GET')return reply(checked(await db.from('teachers').select('*').order('username')).map(userShape));const d=await req.json();if(req.method==='POST'){const username=String(d.username||'').trim().toLowerCase(),name=String(d.displayName||'').trim(),password=String(d.password||'');if(!/^[a-z0-9_]{3,40}$/.test(username)||!name||name.length>60||password.length<10||password.length>128||!['admin','teacher'].includes(d.role))error('请检查账号、姓名、密码长度和权限');const account=checked(await db.auth.admin.createUser({email:username+'@school.invalid',password,email_confirm:true})).user;const saved=await db.from('teachers').insert({id:account.id,username,display_name:name,role:d.role}).select().single();if(saved.error){await db.auth.admin.deleteUser(account.id);throw new Error(saved.error.message)}return reply(userShape(saved.data))}if(req.method==='PATCH'){if(d.id===user.id)error('不能停用自己的账号');if(typeof d.active!=='boolean')error('状态无效');checked(await db.from('teachers').update({active:d.active}).eq('id',d.id));return reply({ok:true})}}
if(route==='/api/students'&&req.method==='GET'){let rows:any[]=[];for(let offset=0;;offset+=1000){const part=checked(await db.from('students').select('*').order('number').range(offset,offset+999));rows=rows.concat(part);if(part.length<1000)break}return reply(rows)}
if(route==='/api/students'&&req.method==='POST'){admin();const d=await req.json();if(d.sample)error('请从提供的名单复制年段、班级、学号、姓名后导入');const rows=d.rows;if(!Array.isArray(rows)||!rows.length||rows.length>3000)error('每次请输入1–3000名学生');const seen=new Set();const items=rows.map((r:any)=>{const o={grade:String(r.grade||'').trim(),class_name:String(r.class_name||'').trim(),number:String(r.number||'').trim(),name:String(r.name||'').trim()};if(!['初一','初二','初三','高一','高二','高三'].includes(o.grade)||[o.class_name,o.number,o.name].some(x=>!x||x.length>60)||seen.has(o.number))error('名册包含空白、重复学号或无效年段');seen.add(o.number);return o});const added=checked(await db.rpc('import_school_roster',{items}));return reply({added,skipped:items.length-added})}
if(route==='/api/incidents'&&req.method==='POST'){const form=await req.formData();const id=String(form.get('id')||'');if(!/^[0-9a-f-]{36}$/.test(id))error('登记标识无效');const old=checked(await db.from('incidents').select('id,created_at,created_by').eq('id',id).maybeSingle());if(old){if(old.created_by!==user.id)error('登记标识冲突');return reply(old)}const s=checked(await db.from('students').select('*').eq('id',String(form.get('studentId')||'')).single());const photo=form.get('photo');if(!(photo instanceof File)||photo.type!=='image/jpeg'||photo.size>8388608||photo.size<10)error('请选择8MB以内的JPG照片');const bytes=new Uint8Array(await photo.arrayBuffer());if(bytes[0]!==255||bytes[1]!==216)error('照片格式无效');const key=user.id+'/'+id+'.jpg';const upload=await db.storage.from('incident-photos').upload(key,bytes,{contentType:'image/jpeg',upsert:false});if(upload.error&&!/already exists|Duplicate/i.test(upload.error.message))throw new Error(upload.error.message);const saved=await db.from('incidents').insert({id,student_id:s.id,grade:s.grade,class_name:s.class_name,name:s.name,number:s.number,photo_key:key,created_by:user.id}).select('id,created_at').single();if(saved.error?.code==='23505'){return reply(checked(await db.from('incidents').select('id,created_at').eq('id',id).single()))}return reply(checked(saved))}
if(route==='/api/photo'){const row=checked(await db.from('incidents').select('photo_key').eq('id',url.searchParams.get('id')||'').single());const signed=checked(await db.storage.from('incident-photos').createSignedUrl(row.photo_key,60));return reply({url:signed.signedUrl})}
if(route==='/api/report'){const r=range(url.searchParams.get('kind')||'week',url.searchParams.get('date')||'');const rows=checked(await db.rpc('school_class_counts',{p_start:r.start,p_end:r.end}));const leaders=[...new Set(rows.map((x:any)=>x.grade))].map(grade=>{const all=rows.filter((x:any)=>x.grade===grade),max=Math.max(...all.map((x:any)=>Number(x.count)));return {grade,max,classes:max>0?all.filter((x:any)=>Number(x.count)===max).map((x:any)=>x.class_name):[]}});const recent=checked(await db.from('incidents').select('id,name,number,grade,class_name,created_at').gte('created_at',r.start).lt('created_at',r.end).order('created_at',{ascending:false}).limit(100));return reply({...r,rows,leaders,total:rows.reduce((n:number,x:any)=>n+Number(x.count),0),recent})}
error('接口不存在',404);
}catch(e:any){console.error(e.message);return reply({error:e.status?e.message:'操作失败：'+e.message},e.status||400)}});
