import http from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {randomBytes,randomUUID,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {mkdirSync,readFileSync,writeFileSync,existsSync,statSync,createReadStream} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const dataDir=path.resolve(process.env.DATA_DIR||path.join(root,'data'));mkdirSync(path.join(dataDir,'photos'),{recursive:true,mode:0o700});
const db=new DatabaseSync(path.join(dataDir,'school.sqlite'));db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');
db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,display_name TEXT NOT NULL,hash TEXT NOT NULL,salt TEXT NOT NULL,role TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS students(id TEXT PRIMARY KEY,grade TEXT NOT NULL,class_name TEXT NOT NULL,number TEXT UNIQUE NOT NULL,name TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS student_class ON students(grade,class_name);
CREATE TABLE IF NOT EXISTS incidents(id TEXT PRIMARY KEY,student_id TEXT NOT NULL REFERENCES students(id),grade TEXT NOT NULL,class_name TEXT NOT NULL,name TEXT NOT NULL,number TEXT NOT NULL,created_at TEXT NOT NULL,photo_key TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id));
CREATE INDEX IF NOT EXISTS incident_date ON incidents(created_at);
CREATE TABLE IF NOT EXISTS login_attempts(key TEXT PRIMARY KEY,count INTEGER NOT NULL,until INTEGER NOT NULL);`);
const port=Number(process.env.PORT||8080),host=process.env.HOST||'127.0.0.1';const secure=process.env.NODE_ENV==='production';const origin=process.env.PUBLIC_ORIGIN||`http://localhost:${port}`;
if(secure&&!origin.startsWith('https://'))throw new Error('生产环境必须设置 PUBLIC_ORIGIN=https://你的域名');
const setupToken=randomBytes(32).toString('hex');const hasUsers=()=>Boolean(db.prepare('SELECT 1 FROM users LIMIT 1').get());
if(!hasUsers())console.log('首次初始化链接（仅管理员使用）：'+origin+'/?setup='+setupToken);
const hash=v=>createHash('sha256').update(v).digest('hex');const publicUser=u=>({id:u.id,username:u.username,displayName:u.display_name,role:u.role,active:Boolean(u.active)});
function json(res,data,status=200){res.writeHead(status,{'Content-Type':'application/json;charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function fail(message,status=400){throw Object.assign(new Error(message),{status})}
function userFor(req){const m=(req.headers.cookie||'').match(/(?:^|;\s*)school_session=([a-f0-9]{64})(?:;|$)/);if(!m)return null;return db.prepare('SELECT users.* FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.hash=? AND sessions.expires>? AND users.active=1').get(hash(m[1]),Date.now())||null}
function session(res,u){const token=randomBytes(32).toString('hex');db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(hash(token),u.id,Date.now()+12*3600000);res.setHeader('Set-Cookie',`school_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${secure?'; Secure':''}`)}
async function read(req,max=9*1024*1024){const parts=[];let size=0;for await(const part of req){size+=part.length;if(size>max)fail('上传内容太大',413);parts.push(part)}return Buffer.concat(parts)}
async function body(req){try{return JSON.parse((await read(req,1024*1024)).toString())}catch(e){if(e.status)throw e;fail('请求格式无效')}}
function admin(u){if(u.role!=='admin')fail('仅管理员可操作',403)}
function newUser(d){const username=String(d.username||'').trim().toLowerCase(),displayName=String(d.displayName||'').trim(),password=String(d.password||'');if(!/^[a-z0-9_]{3,40}$/.test(username))fail('账号须为3–40位字母、数字或下划线');if(!displayName||displayName.length>60)fail('请填写老师姓名');if(password.length<10||password.length>128)fail('密码长度须为10–128位');if(!['admin','teacher'].includes(d.role))fail('账号权限无效');const salt=randomBytes(16).toString('hex'),h=scryptSync(password,salt,64).toString('hex');try{db.prepare('INSERT INTO users(id,username,display_name,hash,salt,role) VALUES (?,?,?,?,?,?)').run(randomUUID(),username,displayName,h,salt,d.role)}catch(e){if(String(e).includes('UNIQUE'))fail('这个账号已存在');throw e}return db.prepare('SELECT * FROM users WHERE username=?').get(username)}
function period(kind,date){if(!['week','month'].includes(kind)||!/^\d{4}-\d{2}-\d{2}$/.test(date))fail('请选择有效统计日期');const day=new Date(date+'T00:00:00+08:00');if(!Number.isFinite(+day)||new Date(+day+28800000).toISOString().slice(0,10)!==date)fail('日期无效');let start,end;if(kind==='week'){start=+day-((new Date(+day+28800000).getUTCDay()+6)%7)*86400000;end=start+7*86400000}else{const [y,m]=date.split('-').map(Number);start=Date.UTC(y,m-1,1)-28800000;end=Date.UTC(y,m,1)-28800000}return {start:new Date(start).toISOString(),end:new Date(end).toISOString(),from:new Date(start+28800000).toISOString().slice(0,10),to:new Date(end+28800000-1).toISOString().slice(0,10)}}
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' blob: data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");if(secure)res.setHeader('Strict-Transport-Security','max-age=31536000');try{const url=new URL(req.url,origin),p=url.pathname;if(p.startsWith('/api/')){
 if(!['GET','HEAD'].includes(req.method)){if(req.headers.origin&&req.headers.origin!==origin)fail('请求来源无效',403);if(req.headers['sec-fetch-site']==='cross-site')fail('请求来源无效',403)}
 const u=userFor(req);
 if(p==='/api/me'&&req.method==='GET')return json(res,{user:u?publicUser(u):null,setup:!hasUsers()});
 if(p==='/api/setup'&&req.method==='POST'){if(hasUsers())fail('系统已初始化',403);const d=await body(req);if(typeof d.token!=='string'||d.token.length!==setupToken.length||!timingSafeEqual(Buffer.from(d.token),Buffer.from(setupToken)))fail('初始化链接无效，请联系服务器管理员',403);const account=newUser({...d,role:'admin'});session(res,account);return json(res,{user:publicUser(account)})}
 if(p==='/api/login'&&req.method==='POST'){const d=await body(req),name=String(d.username||'').trim().toLowerCase();const key=hash(name);const attempt=db.prepare('SELECT * FROM login_attempts WHERE key=?').get(key);if(attempt&&attempt.until>Date.now()&&attempt.count>=8)fail('尝试次数过多，请15分钟后重试',429);const account=db.prepare('SELECT * FROM users WHERE username=?').get(name);const pass=String(d.password||'');if(pass.length>128)fail('账号或密码错误',401);const actual=scryptSync(pass,account?.salt||'nonexistent-user-salt',64);if(!account||!account.active||!timingSafeEqual(actual,Buffer.from(account.hash,'hex'))){const count=attempt&&attempt.until>Date.now()?attempt.count+1:1;db.prepare('INSERT OR REPLACE INTO login_attempts VALUES(?,?,?)').run(key,count,Date.now()+900000);fail('账号或密码错误',401)}db.prepare('DELETE FROM login_attempts WHERE key=?').run(key);session(res,account);return json(res,{user:publicUser(account)})}
 if(!u)fail('请登录后使用',401);
 if(p==='/api/logout'&&req.method==='POST'){const m=(req.headers.cookie||'').match(/school_session=([a-f0-9]{64})/);if(m)db.prepare('DELETE FROM sessions WHERE hash=?').run(hash(m[1]));res.setHeader('Set-Cookie','school_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'+(secure?'; Secure':''));return json(res,{ok:true})}
 if(p==='/api/users'){admin(u);if(req.method==='GET')return json(res,db.prepare('SELECT * FROM users ORDER BY username').all().map(publicUser));if(req.method==='POST')return json(res,publicUser(newUser(await body(req))));if(req.method==='PATCH'){const d=await body(req);if(d.id===u.id)fail('不能停用自己的账号');if(typeof d.active!=='boolean')fail('状态无效');db.prepare('UPDATE users SET active=? WHERE id=?').run(d.active?1:0,String(d.id));db.prepare('DELETE FROM sessions WHERE user_id=?').run(String(d.id));return json(res,{ok:true})}}
 if(p==='/api/students'&&req.method==='GET')return json(res,db.prepare('SELECT * FROM students ORDER BY grade,class_name,number').all());
 if(p==='/api/students'&&req.method==='POST'){admin(u);const d=await body(req);let rows=d.rows;if(d.sample){const f=path.join(dataDir,'sample-roster.json');if(!existsSync(f))fail('尚未放入测试名册，请使用下方批量导入');rows=JSON.parse(readFileSync(f,'utf8'))}if(!Array.isArray(rows)||!rows.length||rows.length>3000)fail('每次请输入1–3000名学生');const seen=new Set();let added=0;db.exec('BEGIN IMMEDIATE');try{for(const r of rows){const grade=String(r.grade||'').trim(),className=String(r.class_name||'').trim(),name=String(r.name||'').trim(),number=String(r.number||'').trim();if(!['初一','初二','初三','高一','高二','高三'].includes(grade)||!className||!name||!number||[className,name,number].some(x=>x.length>60)||seen.has(number))fail('名册包含空白、重复学号或无效年段');seen.add(number);const old=db.prepare('SELECT * FROM students WHERE number=?').get(number);if(old&&(old.name!==name||old.grade!==grade||old.class_name!==className))fail('学号 '+number+' 已关联其他学生或班级');if(!old){db.prepare('INSERT INTO students VALUES(?,?,?,?,?)').run(randomUUID(),grade,className,number,name);added++}}db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return json(res,{added,skipped:rows.length-added})}
 if(p==='/api/incidents'&&req.method==='POST'){const bytes=await read(req);const form=await new Request(origin,{method:'POST',headers:{'Content-Type':req.headers['content-type']||''},body:bytes}).formData();const id=String(form.get('id')||'');if(!/^[0-9a-f-]{36}$/.test(id))fail('登记标识无效');const old=db.prepare('SELECT id,created_at FROM incidents WHERE id=?').get(id);if(old)return json(res,old);const s=db.prepare('SELECT * FROM students WHERE id=?').get(String(form.get('studentId')||''));if(!s)fail('请从名册选择学生');const photo=form.get('photo');if(!(photo instanceof File)||photo.type!=='image/jpeg'||photo.size>8*1024*1024||photo.size<10)fail('请选择8MB以内的JPG照片');const content=Buffer.from(await photo.arrayBuffer());if(content[0]!==255||content[1]!==216)fail('照片格式无效');const key=id+'.jpg';writeFileSync(path.join(dataDir,'photos',key),content,{mode:0o600});const created_at=new Date().toISOString();db.prepare('INSERT INTO incidents VALUES(?,?,?,?,?,?,?,?,?)').run(id,s.id,s.grade,s.class_name,s.name,s.number,created_at,key,u.id);return json(res,{id,created_at})}
 if(p==='/api/photo'&&req.method==='GET'){const row=db.prepare('SELECT photo_key FROM incidents WHERE id=?').get(url.searchParams.get('id')||'');if(!row)fail('照片不存在',404);const file=path.join(dataDir,'photos',row.photo_key);if(!existsSync(file))fail('照片不存在',404);res.writeHead(200,{'Content-Type':'image/jpeg','Cache-Control':'private,no-store'});return createReadStream(file).pipe(res)}
 if(p==='/api/report'&&req.method==='GET'){const range=period(url.searchParams.get('kind')||'week',url.searchParams.get('date')||'');const rows=db.prepare('WITH classes AS (SELECT grade,class_name FROM students UNION SELECT grade,class_name FROM incidents), counts AS (SELECT grade,class_name,COUNT(*) AS count FROM incidents WHERE created_at>=? AND created_at<? GROUP BY grade,class_name) SELECT classes.grade,classes.class_name,COALESCE(counts.count,0) AS count FROM classes LEFT JOIN counts ON classes.grade=counts.grade AND classes.class_name=counts.class_name ORDER BY classes.grade,count DESC,classes.class_name').all(range.start,range.end);const leaders=[...new Set(rows.map(r=>r.grade))].map(grade=>{const all=rows.filter(r=>r.grade===grade),max=Math.max(...all.map(r=>r.count));return {grade,max,classes:max>0?all.filter(r=>r.count===max).map(r=>r.class_name):[]}});const recent=db.prepare('SELECT incidents.id,name,number,grade,class_name,created_at,users.display_name AS teacher FROM incidents JOIN users ON users.id=created_by WHERE created_at>=? AND created_at<? ORDER BY created_at DESC LIMIT 100').all(range.start,range.end);return json(res,{...range,rows,leaders,total:rows.reduce((n,r)=>n+r.count,0),recent})}
 fail('接口不存在',404);
 }
 if(!['GET','HEAD'].includes(req.method))fail('请求方式不支持',405);const asset=path.resolve(root,'web-dist','.'+decodeURIComponent(p));if(!asset.startsWith(path.join(root,'web-dist')+path.sep))fail('路径无效',404);const file=existsSync(asset)&&statSync(asset).isFile()?asset:path.join(root,'web-dist/index.html');const types={'.html':'text/html;charset=utf-8','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png'};res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':path.extname(file)==='.html'?'no-cache':'public,max-age=86400'});if(req.method==='HEAD')return res.end();createReadStream(file).on('error',()=>res.destroy()).pipe(res);
 }catch(e){if(!e.status)console.error('Request failed:',e.message);if(!res.headersSent)json(res,{error:e.status?e.message:'服务暂不可用，请重试'},e.status||500);else res.destroy()}});
server.listen(port,host,()=>console.log(`校园记录已启动：${origin}`));
