const config=(window as any).SCHOOL_CONFIG;
const key='school-auth-session';
let session:any;try{session=JSON.parse(sessionStorage.getItem(key)||'null')}catch{session=null}
let refreshing:Promise<any>|null=null;
function save(s:any){session=s;if(s)sessionStorage.setItem(key,JSON.stringify(s));else sessionStorage.removeItem(key)}
const json=(d:any,status=200)=>new Response(JSON.stringify(d),{status,headers:{'Content-Type':'application/json'}});
async function refresh(){if(!session?.refresh_token)return;if(!refreshing)refreshing=fetch(config.url+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:config.key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})}).then(async r=>{const d=await r.json();if(r.ok)save(d);else save(null)}).finally(()=>{refreshing=null});return refreshing}
export async function fetchApi(path:string,options:RequestInit={}):Promise<Response>{if(!config?.url)return fetch(path,options);if(path==='/api/login'){const d=JSON.parse(String(options.body));const username=String(d.username||'').trim().toLowerCase();const r=await fetch(config.url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:config.key,'Content-Type':'application/json'},body:JSON.stringify({email:username.includes('@')?username:username+'@school.invalid',password:d.password})});const result=await r.json();if(!r.ok)return json({error:'账号或密码错误，或尝试过于频繁，请稍后重试'},r.status);save(result);const me=await fetchApi('/api/me');const who=await me.json();if(!who.user){save(null);return json({error:'此账号尚未开通或已停用，请联系管理员'},403)}return json(who)}if(path==='/api/logout'){if(session)await fetch(config.url+'/auth/v1/logout',{method:'POST',headers:{apikey:config.key,Authorization:'Bearer '+session.access_token}});save(null);return json({ok:true})}if(!session)return path==='/api/me'?json({user:null,setup:false}):json({error:'请登录后使用'},401);if(session.expires_at&&session.expires_at*1000<Date.now()+60000)await refresh();if(!session)return json({error:'登录已过期，请重新登录'},401);const local=new URL(path,'http://local');local.searchParams.set('route',local.pathname);const headers=new Headers(options.headers);headers.set('apikey',config.key);headers.set('Authorization','Bearer '+session.access_token);return fetch(config.url+'/functions/v1/school-api?'+local.searchParams,{...options,headers})}
export async function openPhoto(id:string){const win=window.open('about:blank','_blank');try{if(!config?.url){if(win)win.location.href='/api/photo?id='+encodeURIComponent(id);return}const r=await fetchApi('/api/photo?id='+encodeURIComponent(id));const d=await r.json();if(!r.ok)throw new Error(d.error);if(win)win.location.href=d.url}catch(e){win?.close();throw e}}
