import {fetchApi,openPhoto} from './api';
import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import Register from '../app/register';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {ClipboardCheck} from 'lucide-react';
import '../app/globals.css';
import {UserContext} from './context';
function App(){const [user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[setup,setSetup]=useState(false),[displayName,setDisplayName]=useState('');useEffect(()=>{fetchApi('/api/me').then(r=>r.json()).then((d:any)=>{setUser(d.user);setSetup(d.setup)}).catch(()=>setError('无法连接服务器，请刷新重试')).finally(()=>setLoading(false))},[]);async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetchApi(setup?'/api/setup':'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password,displayName,token:new URLSearchParams(location.hash.slice(1)).get('setup')||''})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setUser(d.user);history.replaceState(null,'',location.pathname);setPassword('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}if(loading)return <main><p className="empty">正在连接校园记录…</p></main>;if(user)return <UserContext.Provider value={user}><Register/><div style={{maxWidth:600,margin:'0 auto 30px',padding:'0 20px',display:'flex',justifyContent:'space-between',alignItems:'center'}}><span className="muted">{user.displayName} · {user.role==='admin'?'管理员':'值班老师'}</span><Button variant="outline" onClick={async()=>{await fetchApi('/api/logout',{method:'POST'});setUser(null)}}>退出登录</Button></div></UserContext.Provider>;return <main className="login"><span className="brand" style={{display:'inline-flex'}}><ClipboardCheck size={28}/></span><section className="title"><span>校园记录</span><h1>{setup?'创建管理员账号':'值班老师登录'}</h1><p className="muted">{setup?'首次使用，由学校管理员完成初始化。':'登录后登记现场情况，查看班级统计。'}</p></section><form className="card" onSubmit={login}>{error&&<p className="notice error" role="alert">{error}</p>}{setup&&!new URLSearchParams(location.hash.slice(1)).get('setup')&&<p className="notice">请使用服务器启动时生成的初始化链接。</p>}<label>账号<Input required autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder="请输入老师账号"/></label>{setup&&<label>显示姓名<Input required value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="管理员姓名"/></label>}<label>密码<Input required type="password" autoComplete={setup?'new-password':'current-password'} value={password} minLength={setup?10:undefined} onChange={e=>setPassword(e.target.value)} placeholder={setup?'至少10位':'请输入密码'}/></label><Button className="submit" disabled={busy}>{busy?'正在登录…':setup?'创建管理员并登录':'登录'}</Button><p className="muted" style={{marginTop:18}}>{setup?'请保存好管理员账号和密码。':'账号由学校管理员开通，忘记密码请联系管理员。'}</p></form></main>}
createRoot(document.getElementById('root')!).render(<App/>);
